### ISSUE TITLE
The WebGPU option does not work on Firefox Nightly

### ISSUE THREAD

**Issue by xNul** [cheahjs/palworld-steam-id-to-player-uid#2]
Firefox Nightly has WebGPU support, but your code here doesn't seem to work with it. This could be a problem on Firefox Nightly's side but I thought I should mention it.

Firefox Nightly console log
![image](https://github.com/cheahjs/palworld-steam-id-to-player-uid/assets/894305/6413d5cb-f3d1-4c16-97b3-54b496a5e6ae)

**Comment by cheahjs** [comment]
https://github.com/cheahjs/palworld-steam-id-to-player-uid/commit/8b21d8629deb4f52703254d971a6d2e61bb0abe9 fixes Firefox (and wgpu) compat, but seems to run slower than on Chrome (on AMD APU at least)

**Comment by cheahjs** [comment]
I'll just mention that https://github.com/magicbear/palworld-server-toolkit has also been adding conversion support, but only for the easy paths (attach any character to a Steam ID, and convert a Steam UID to a NoSteam UID)
