### ISSUE TITLE
Store static hash mappings somewhere for users to lookup instead of running the bruteforce

### ISSUE THREAD

**Issue by cheahjs** [cheahjs/palworld-steam-id-to-player-uid#4]
Given the 2^32 possible Steam IDs, it should be feasible to pre-compute all Steam ID<>UID mappings, and have the web browser fetch it instead of bruteforcing.

Bruteforcing should still be available, in the event that the pre-computed mappings are not available, as hosting costs are non-negligible. Storage calculations (minimum):

```
2^32 4-byte Steam IDs
Each Steam ID maps onto 2 4-byte UIDs (Steam and No Steam variants).
2^32 * (4+4+4) = 51539607552 bytes = ~52GB of raw storage with no indexing/metadata
```

**Comment by asdf4w3t5** [comment]
is it possible to gzip / zstd that data and stream from the archive? it'd probably only be like 5gb then
