### ISSUE TITLE
Is there any function or project in .NET Core to finish the job SteamIDtoUID?

### ISSUE THREAD

**Issue by shenzhoukai** [cheahjs/palworld-steam-id-to-player-uid#5]
I've tried to install CityHash in .NET Core but I cannot get the low bits and high bits from the city64 long value.

**Comment by shenzhoukai** [comment]
Or PHP、JS etc. so that I can deploy it as an API like https://api.my-pal-api.com/convert-id?SteamID=xxx and response an UID

**Comment by cheahjs** [comment]
CityHash has libraries in most languages. You need to ensure that all operations are done with unsigned integers (ulong/uint in .Net). If the language does not support unsigned integers (like Javascript or Python), then you'll have to figure out how to perform the equivalent arithmetic and bitwise operations in that language.
